### ISSUE TITLE
Can't debug

### ISSUE THREAD

**Issue by dadamschi** [gfk-ba/senbot#16]
I am not sure what I am doing wrong, but I cloned the repository, ran the install, and cannot debug the project.

I am using IntelliJ and would like to see more about how this framework works but I really cannot do that when I can't debug the project.

Any assistance would be greatly appreciated.

**Comment by joostschouten** [comment]
How and what are you running (maven, IntelliJ test runner, maven though IntelliJ, on of our tests, one of your own, etc.)? Please be as specific as you can. I have no issues with debugging so I'm sure it is a solvable problem ;-)

**Comment by dadamschi** [comment]
Sorry about that rookie mistake in a couple ways.

I am using maven with IntelliJ. I had forgotten about useForkMode=false which resolved my debugging issue.

I had also forgotten to include this information. When I went back to update my comment I did not see it.

I am now working on walking through the stack and hopefully will be able to understand more of the app today.
