### ISSUE TITLE
Cannot run specific feature file

### ISSUE THREAD

**Issue by dadamschi** [gfk-ba/senbot#17]
Given I am new to Cucumber and SenBot
When I try to specify a feature to test in the SenBotDemo (test -DforkMode=never -Dfeatures=features/WebApp/Chapter2/CucumberTest.feature)
Then All of the features are running

Am I missing something?

**Comment by joostschouten** [comment]
In file: com.gfk.senbotdemo.cucumber.tests.WebAppTest try removing the line:         

features = "features", 

This overrides the commandline settings in the current version of cucumber-jvm. I believe this will change on the next update to the latest cucumber-jvm.

**Comment by dadamschi** [comment]
That worked. Thanks for the help.
