### ISSUE TITLE
When run with -Parallel then Jenkins/CI does not recognize/report failing tests

### ISSUE THREAD

**Issue by nreijmersdal** [gfk-ba/senbot#2]
When a SenBotRunner project is started with -Parallel the tests don't mark the project failed when a error occurs leading to the false assumption the tests are running fine.

Improve Parallel execution to trigger correct/better fails

**Comment by marcodejongh** [comment]
@joostschouten @nreijmersdal is this still happening or can we close this?

**Comment by nreijmersdal** [comment]
No idea and I cannot test it myself at this stage, will close it to clean up.
