### ISSUE TITLE
Parsing output to database

### ISSUE THREAD

**Issue by dadamschi** [gfk-ba/senbot#20]
I have been looking through the code for last few days trying to find the best location to trap  test case results and put them in to a database. I have not been having much luck and was wondering if you could point me in the right direction.

Ideally anything I write I would contribute back in to the project. 

The format of this framework is solid and is something I would like to use for a few products I am testing. Reporting is always an issue. Ideally I would like get the Cucumber scenario and and all steps and each result in to a MySQL table. On top of that, I would like to report the browser for each scenario and its steps.

Any help is appreciated.

**Comment by joostschouten** [comment]
the easiest thing is to parse the output of SENBOT_PROJECT_ROOT/target/test-results/result.json once the run has completed. The [cucumber-reporting](http://www.masterthought.net/section/cucumber-reporting) plugin we are using does the same. Reporting is a bit tricky especially in combination with multithreading and I have a few improvements planned. For now however, the json output is your best bet.
