### ISSUE TITLE
The senbot example tests do not all run on all "modern" browsers.

### ISSUE THREAD

**Issue by nreijmersdal** [gfk-ba/senbot#3]
Not all of our example tests run on all browsers, for example some tests fail on IE9 and Firefox.

Fix the tests to run on all browsers, lets start with Chrome, IE9 and Firefox and later add Safari and Opera.

**Comment by marcodejongh** [comment]
@joostschouten @nreijmersdal is this still happening or can we close this?

**Comment by nreijmersdal** [comment]
Not really a bug, more a feature request. Will close it.
