### ISSUE TITLE
Archetype tests all fail

### ISSUE THREAD

**Issue by nreijmersdal** [gfk-ba/senbot#5]
After creating a new archetype with the mvn archetype:generate it builds, but all the example tests supply seem to fail.

Fix the archetype tests

**Comment by nreijmersdal** [comment]
Shortly looking at the tests I think they are meant to fail, but I think this is a bad starting point.
Maybe better to make two simple tests that at-least run succesfully

**Comment by joostschouten** [comment]
They should all work. I could have a look at it one of these days.

**Comment by nreijmersdal** [comment]
They do work, but some steps are not implemented, which is fine.
Still the Archetype could use some cleanup, but not in this scope :)

**Comment by joostschouten** [comment]
https://github.com/gfk-ba/senbot/commit/eb078eca9a7539c992d609a6673fc811bd33dacc fixed this issue.
